module.exports = {
    up: queryInterface => queryInterface.bulkInsert(
      'lessons',
      [
          // Grade 1
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade1',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade1',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade1',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade1',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade1',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 2
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade2',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade2',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade2',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade2',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade2',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 3
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade3',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade3',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade3',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade3',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade3',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 4
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade4',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade4',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade4',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade4',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade4',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 5
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade5',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade5',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade5',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade5',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade5',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 6
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade6',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade6',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade6',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade6',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade6',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 7
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade7',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade7',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade7',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade7',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade7',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 8
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade8',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade8',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade8',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade8',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade8',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 9
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade9',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade9',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade9',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade9',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade9',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        //Grade 10
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade10',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade10',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade10',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade10',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade10',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 11
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade11',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade11',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade11',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade11',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade11',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Grade 12
        {
            subjectName: 'English',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade12',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Mathematics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade12',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Physics',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade12',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Chemistry',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade12',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            subjectName: 'Biology',
            startdate: new Date(),
            durationMinutes: 60,
            grade: 'grade12',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
      ],
      {}
    ),
  
    down: queryInterface => queryInterface.bulkDelete('lessons', null, {})
  };